project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03-SPAA.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

