project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
        - text: "In-class Exercise 6"
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
        - text: "In-class Exercise 7: GLSA"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07-GLSA.html"
        - text: "In-class Exercise 7: EHSA"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07_EHSA.html"
        - text: "In-class Exercise 8: gwr"
          href: "In-class_Ex/In-class_Ex08/In-class_Ex08_gwr.html"
        - text: "In-class Exercise 9: gwML"
          href: "In-class_Ex/In-class_Ex09/In-class_Ex09_gwML.html"
        - text: "In-class Exercise 10: GeoAcc"
          href: "In-class_Ex/In-class_Ex10/In-class_Ex10_GeoAcc.html"
        - text: "In-class Exercise 11: SIM"
          href: "In-class_Ex/In-class_Ex11/In-class_Ex11_SIM.html"  
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"  
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

